// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DoCalculate(arg1:string,arg2:main.PROCESS_TYPE):Promise<string>;
