name: Build Wails App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Wails CLI
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Inject secret keys
      run: |
        echo "export OPEN_AI=${{ secrets.OPEN_AI }}" >> $GITHUB_ENV
        # echo "export DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

    - name: Build Wails App
      run: |
        wails build

    - name: Archive production build
      uses: actions/upload-artifact@v3
      with:
        name: wails-app
        path: ./build/bin/*  # Path to the built binary

    - name: Run Basic Test
      run: |
        ./build/bin/calculator --version
        ls -la ./build/bin/calculator
